[package]
name = "self-awareness"
version = "0.1.1"
edition = "2024"

[dependencies]
image = { version = "0.24", features = ["webp"] }
ratatui = "0.29"
crossterm = "0.28"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
anyhow = "1"
dirs = "5"
aes-gcm = "0.10"
rand = "0.8"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dxgi",
]}
sha2 = "0.11.0"
argon2 = { version = "0.5.3", features = ["alloc"] }
rpassword = "7.5.1"

[profile.release]
opt-level = 3
strip = true
lto = true
